"""empty message

Revision ID: 44f90b0e21b2
Revises: f7b06851ff7e
Create Date: 2021-03-22 16:53:32.586951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f90b0e21b2'
down_revision = 'f7b06851ff7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('self_affirmations', 'date')
    op.drop_column('self_affirmations', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_affirmations', sa.Column('title', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('self_affirmations', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
